### ISSUE TITLE
Error Opening Links using button in message

### ISSUE THREAD

**Issue by aidab98** [cristianoag/microsoft-teams-apps-company-communicator#13]
Hello,

When user is creating a new message, the link added in the button is tested using the preview method and the correct link opens. However, once message is sent out, the button opens a different link than the one seen in the preview.

This is a problem as the link opening is inconsistent between the actual message and the one in the preview.
It's the same link but in preview opens one and in the actual message opens another.

Is this a bug?

**Comment by cristianoag** [comment]
Fixed on CC Community Fork - v4.45
