### ISSUE TITLE
Company Communicator failed to upload CSV as Error the file is too big

### ISSUE THREAD

**Issue by MSFTHarry** [cristianoag/microsoft-teams-apps-company-communicator#19]
There is an issue from my customer that when they uploads CSV with a picture it keeps always showing below error the file is too big, but in fact even there is only one email address with the CSV, it will be failed still except remove the image.

May I know if the app counts the whole things size together here? What's the limitation?
![169306893-0a24fc54-4e93-40a2-81db-5ca7e775759c](https://user-images.githubusercontent.com/105835083/169436162-bd1dabc1-587a-4969-853d-e394b3f0e5cd.jpg)
.

**Comment by cristianoag** [comment]
What is the size of the CSV file. The file size combined with the size of the card cannot go over 32kb.

**Comment by maye-vargas** [comment]
@MSFTHarry or @cristianoag, Do you have the template for said CSV?

**Comment by grsandeep** [comment]
For me it is saying the .csv is uploaded successfully, however when we send a message it is showing as "Syncing recipients..." and the message is not delivered

Can you also provide the template for CSV

@cristianoag

**Comment by grsandeep** [comment]
Update -

The "Synching recipients" message is gone but the message is not delivered.


In the SyncCSVActivity logs i see the below -

User "UPN" is invalid. Code: Request_ResourceNotFound Message: Resource '"UPN' does not exist or one of its queried reference-property objects are not present. 

However, the user is available in the directory
