### ISSUE TITLE
Company Communicator Configuration Error

### ISSUE THREAD

**Issue by nahcyrret** [cristianoag/microsoft-teams-apps-company-communicator#24]
The scope has been defined but still get the following error. How can I fix this?

You must define scope(s) before you can authorize a client application  
![AddClientApp](https://user-images.githubusercontent.com/39899353/170647679-f03a3dcd-691c-48b4-b86c-126ed859726a.PNG)

**Comment by cristianoag** [comment]
You just need to select the scope. There is a box on the left side that seems not selected.
