### ISSUE TITLE
Vault to Long name

### ISSUE THREAD

**Issue by json94** [cristianoag/microsoft-teams-apps-company-communicator#28]
Hi

We tried to Upgrade our existing solution to V5 but the name of the existing solutions is to long for the vault. 

    "status": "Failed",
    "error": {
        "code": "VaultNameNotValid",
        "message": "The vault name 'mgbCompanyCommunicatorvault' is invalid. A vault's name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens. Follow this link for more information: https://go.microsoft.com/fwlink/?linkid=2147742"
    }

is there an option that we can specify another Vault name, then the generated one? maybe in the template.

**Comment by cristianoag** [comment]
Vault has a limit on the name size. I do recommend using short base names so you avoid issues when the setup is creating the vault. You went beyond the limit as you are using a long base name.
