### ISSUE TITLE
Azure Deployment JSON is out of Date.

### ISSUE THREAD

**Issue by gavinjhunter** [cristianoag/microsoft-teams-apps-company-communicator#30]
The deployment template json is out of date and has the old URL:
https://github.com/cristianoag/microsoft-teams-company-communicator-app.git

and needs to be updated to:
https://github.com/cristianoag/microsoft-teams-apps-company-communicator.git

Updating this manually in "Git Repo URL" during deployment fixes this but best fixed at the source.

**Comment by cristianoag** [comment]
Fixed.
