### ISSUE TITLE
Permissions needed. Ask your IT admin to enable this option for you in company communicator

### ISSUE THREAD

**Issue by JuliettaCOL** [cristianoag/microsoft-teams-apps-company-communicator#34]
Hello Team

I have configured this version and currently I have a problem with the permissions to send messages to M365 groups, Distribution groups, Security groups, permissions have been assigned in the AppGraph as indicated in the step by step https://github.com/cristianoag/microsoft-teams-apps-company-communicator/wiki/Deployment-Guide#4-add-permissions-to-your-app, even additional ones were assigned to validate the operation and it is not possible for the authors to have access. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/107083999/182655873-2eee267a-acd6-4e31-8489-847bb35aa689.png)

What other settings or permissions should be taken into account?

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/107083999/182655952-e8e861f0-4f9f-41c8-8234-8e05787d79ac.png)

I have applied some solutions published here but to no avail:
- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/246
- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#3-send-in-chat-to-members-of-the-following-m365-groups-distribution-groups-or-security-groups-option-is-disabled
- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/647

**Comment by cristianoag** [comment]
Please check if the values for the secrets are connect on KeyVault.
