### ISSUE TITLE
chat message while composing

### ISSUE THREAD

**Issue by Maxiz80** [cristianoag/microsoft-teams-apps-company-communicator#37]
Hi.
I'm using version 5.1.2 in business environment.
All is working correctly but I've noticed that if I'm composing a message and in the meantime I receive a chat message and try to open it I cannot close the composing window.
It's responsive, I can save the message as draft BUT I cannot close the window of CC to reply at the chat message.
The only way is to close Teams totally

**Comment by cristianoag** [comment]
That is a known issue. You need to finish the compose operation before switch over to chat.
