### ISSUE TITLE
Azure function app error after upgrade to 5.13

### ISSUE THREAD

**Issue by Funtimefrank22** [cristianoag/microsoft-teams-apps-company-communicator#38]
Hi All, ran the upgrades this week to version 5.13 and all showing as 'success (active)' however on the function app I now get this error - System.Private.CoreLib: Value cannot be null. (Parameter 'value'). - and the function app is not running. Has anyone else encountered this issue or know how to resolve?

![Azure](https://user-images.githubusercontent.com/116903247/198678201-457f7c69-3946-4e91-a1ef-190127b00ea9.PNG)
![Azure2](https://user-images.githubusercontent.com/116903247/198678323-25376038-4c0f-4d3d-af8c-dcbc7a1ef5e8.PNG)

Most grateful for any assistance, I've not experienced any issues with previous upgrades.

Thanks

**Comment by cristianoag** [comment]
Are you using any firewall rules, ACLs, or restrictions between the storage account and the functions? That happens when functions cannot mount the drives.

**Comment by snailCorpse** [comment]
I also got this error. I found the error log to read:
C:\home\site\repository\Source\CompanyCommunicator.Common\Repositories\NotificationData\NotificationDataEntity.cs(282,5): warning SA1508: A closing brace should not be preceded by a blank line.
