### ISSUE TITLE
We can't upload the app because there's already an app in the catalog with the same app ID. To upload a new app, change the app ID and try again. To update an existing app, go to the app details page

### ISSUE THREAD

**Issue by JamaliShoaib** [cristianoag/microsoft-teams-apps-company-communicator#47]
All I followed the whole procedure by registering applications and their App ID and Secret ID and completed azure step.
But unfortunately once i try to upload on teams it is throwing error "We can't upload the app because there's already an app in the catalog with the same app ID. To upload a new app, change the app ID and try again. To update an existing app, go to the app details page"

<img width="455" alt="CaptureError3" src="https://user-images.githubusercontent.com/29330750/223044506-246e232c-cc96-49ea-a78b-f2b11ecdc80e.PNG">

**Comment by tiagomiotto** [comment]
Do you have any other instances of the Company Communicator on the same tenant? If so, the Users Teams App needs to have unique App Ids.
- If that is the case, change the ID on your manifest and the App Service configuration to have a unique value.
- User App ExternalId [Optional]: Default value is 148a66bb-e83d-425a-927d-09f4299a9274. This MUST be the same id that is in the Teams app manifest for the user app. 


If that's not the case, check the list of applications on the tenant, as the application should be there already, causing a conflict.
