### ISSUE TITLE
Can add format text Summary ?

### ISSUE THREAD

**Issue by Fadel1949** [cristianoag/microsoft-teams-apps-company-communicator#48]
Hi Can you add format text Like this ? how to edit 

![image](https://user-images.githubusercontent.com/126840838/233895898-fc862d40-55c4-4a11-b698-2f20439e592b.png)

Thank you.

**Comment by Fadel1949** [comment]
@cristianoag  can you add format Like this ? or recommended for edit this format

**Comment by cristianoag** [comment]
You can format using markdown. Those buttons are just shortcuts to include markdown tags into the summary.
