### ISSUE TITLE
Deployment failure for the app service

### ISSUE THREAD

**Issue by githubclaw** [cristianoag/microsoft-teams-apps-company-communicator#49]
This a new deployment using https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fcristianoag%2Fmicrosoft-teams-apps-company-communicator%2Fmaster%2FDeployment%2Fazuredeploy.json

When we add the company communicator author app to Teams, it shows the below error. 
![image](https://user-images.githubusercontent.com/128158217/236662683-003295f3-3ffd-4207-bf06-f2a6b3cc7f5d.png)

I checked in the deployment center and found this error, 
![image](https://user-images.githubusercontent.com/128158217/236662801-c326fe88-465e-4346-95a9-0aa233081bc7.png)

I've synced several times and the same error came out, May I know how I should solve this, please? @tiagomiotto Here are the logs
[Error_Redeploy_.txt](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/files/11414135/Error_Redeploy_.txt)

**Comment by tiagomiotto** [comment]
Seems to be an error with npm. @cristianoag have you seen this before?

**Comment by cristianoag** [comment]
Please deploy the master_v5.30 please. Don't use the default master branch.
