### ISSUE TITLE
Issue with accessing new message in author app via Teams - Error: There was a problem reaching the app. 

### ISSUE THREAD

**Issue by saranRK05** [cristianoag/microsoft-teams-apps-company-communicator#50]
Issue with access the author app via Teams - Error: There was a problem reaching the app. 

Recently we have some users experiencing issue when tying to create a new message in CC Author app. 

Last successful  was 3rd may 2023. 

@cristianoag 

Kindly assist. 

![MicrosoftTeams-image (16)](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/133250693/d93e6e12-e254-4a70-9ebf-8967c8ff9c3a)

**Comment by saranRK05** [comment]
YEs, I have performed the Sync and restarted the App service. 
With regards to error on App Insights I can see the attached. Which one is that you wanted me to check?
![Screen Shot](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/133250693/e5fde436-bbe4-4784-97ca-bbe2953e4207)

**Comment by cristianoag** [comment]
That is the cause of the problem. I think you were running v4 and when you clicked sync you compiled v5 over a v4 configuration.

To quickly fix your deployment change the branch on the App Service and each one of the Azure functions to master-v4.51 and resync.

Then when everything is back to normal, check the documentation on how to upgrade it to v5.

Cristiano.
________________________________

**Comment by saranRK05** [comment]
Thanks Chris, This has an issue even before we initiated a sync.

**Comment by cristianoag** [comment]
Check if you have an Azuke Key vault resource created. If not, go ahead and resync all resources I mentioned previously to master-v4.51. Then we can troubleshoot.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SammyRasha** [comment]
Thanks @cristianoag - I will work with @saranRK05 to determine if its v4 or v5. I recommended resyncing all the app services and functions but i didn't check if it was v5 for sure, as it was a newer deployment and assumed it was. I will verify and do the redeployment if its v4 and get back to you next week.

**Comment by cristianoag** [comment]
If it is v5 and is not working let me know and we will troubleshoot.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
