### ISSUE TITLE
Low Image Quality

### ISSUE THREAD

**Issue by lgarciab0717** [cristianoag/microsoft-teams-apps-company-communicator#53]
Good afternoon, I have detected that when I load an image in a message the quality of it drops considerably, and the loading of files by URL does not work correctly, how can I solve this problem?

**Comment by cristianoag** [comment]
Please enable the blob storage for images. More info on how to enable can be found here https://tech-peanuts.com/2022/01/24/company-communicator-upload-images-to-azure-blob-storage/
