### ISSUE TITLE
Got error when sent out message

### ISSUE THREAD

**Issue by yenpoonms** [cristianoag/microsoft-teams-apps-company-communicator#54]
We have a new installation, but we encountered the error below when sending message.

Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> Microsoft.Azure.WebJobs.Script.HostInitializationException : One or more loaded extensions do not meet the minimum requirements. For more information see [https://aka.ms/func-min-extension-versions.ExtensionStartupType](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Ffunc-min-extension-versions.ExtensionStartupType&data=05%7C01%7Cyen.poon%40microsoft.com%7C9fcbca7b43064eb98cc108dba286576c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282470112267293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ljyKbcGJdxm90QNrb7nOJ05dwReZAyqhq64HknFhQXU%3D&reserved=0) DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later.ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later.   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.ValidateExtensionRequirements(List`1 startupTypes) at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 330   at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 216   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)   at System.Lazy`1.CreateValue()   at System.Lazy`1.get_Value()   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.<AddScriptHostCore>b__8(IWebJobsStartupTypeLocator locator) at /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 253   End of inner exception

**Comment by luishdemetrio** [comment]
This issue has been open for a long time and most likely resolved by now, so I'm going to close it.
