### ISSUE TITLE
Keep loading when opening "Draft" messages

### ISSUE THREAD

**Issue by yenpoonms** [cristianoag/microsoft-teams-apps-company-communicator#55]
We have an installation running for few months already, started from few weeks ago, the screen will keep loading for some of the draft messages which didn't happen before.

**Comment by cristianoag** [comment]
Have you checked if your secrets expired?

**Comment by luishdemetrio** [comment]
This issue has been open for a long time and most likely resolved by now, so I'm going to close it.
