### ISSUE TITLE
Buttons Click Tracking

### ISSUE THREAD

**Issue by uvagrita** [cristianoag/microsoft-teams-apps-company-communicator#57]
I have a problem with the tracking button, there are more clicks on the tracking button than people reading the message, why is this?
![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/144832847/2d8e5e47-bbe8-4e78-a19e-46c93f5c1aed)

**Comment by CRVieiras** [comment]
Enfrentando o mesmo problema aqui

**Comment by cristianoag** [comment]
Due to a recent change with the Teams client, the strategy we used to track reads is being affected. We are working in a fix that will be release in a few days.

**Comment by cristianoag** [comment]
For everybody using master-v5.30, you just need to resync the App Service and all functions. For the ones using master-v5.31 it is required to create a new front door rule according to the following screenshot

![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/48498602/4b878ab1-c841-4ac0-94e5-7b477c088ecd)

**Comment by luishdemetrio** [comment]
It was fixed for the versions master-v4.51, master-v5.30 and master-v5.31
