### ISSUE TITLE
Sent Message Stuck in Queue

### ISSUE THREAD

**Issue by mustafafarooq** [cristianoag/microsoft-teams-apps-company-communicator#61]
The sent message is stuck in queue upon checking the Azure functions there is this notification at top. I have deployed the app from the master-v5.31 repo.

axcommunicatorapp-function
Microsoft.Teams.Apps.CompanyCommunicator.Send.Func: Could not load file or assembly 'Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

axcommunicatorapp-prep-function
Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func: Could not load file or assembly 'Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

axcommunicatorapp-data-function
Microsoft.Teams.Apps.CompanyCommunicator.Data.Func: Could not load file or assembly 'Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by luishdemetrio** [comment]
Hello @mustafafarooq, could you please let me know which version of the functions you are using? You can find this information in the Azure portal under Functions > Configuration > Function runtime settings. The version should be ~4.

**Comment by mustafafarooq** [comment]
Data Function 
![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/1696026/69e2d4d9-5624-450f-8df5-04b843a998bb)


Function
![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/1696026/76470e5c-eb7a-43f3-baf0-b9eabecf02c7)


Prep Function 
![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/1696026/f9168952-f049-4eae-a4fc-315e1513dfbe)

**Comment by luishdemetrio** [comment]
Hi @mustafafarooq, thanks for your patience. You need to go to Azure portal, for each function, navigate to Configuration and change the FUNCTIONS_EXTENSION_VERSION to ~4 and restart them.

<img width="263" alt="image" src="https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/49683427/57cb0c3d-0835-4929-a569-de224e17ff25">

**Comment by luishdemetrio** [comment]
I am closing this issue. Please reopen it in case the problem persists.
