### ISSUE TITLE
CSV file is too big

### ISSUE THREAD

**Issue by ostromecko** [cristianoag/microsoft-teams-apps-company-communicator#66]
Hi, I have recently faced an issue with uploading CSV file. I cannot find in documentation anything about limitations for uploaded files. 
The error says like this: The CSV is too big. Needs to be smaller than:  30141 bytes. - can it be bypassed by some setting in the configuration, or it works by design?

**Comment by luishdemetrio** [comment]
It seems that the limit is set by design.
