### ISSUE TITLE
messages get stuck in the queue

### ISSUE THREAD

**Issue by MarkusMGB** [cristianoag/microsoft-teams-apps-company-communicator#70]
We are having issues that our messages get stuck in the queue and are not send. Last time working was on 9.11. Is this related due latest issues?

Thanks

Markus

**Comment by luishdemetrio** [comment]
Hi @MarkusMGB, the latest issue was preventing the CC Authors app to load. What version (branch) are you using? Depending on the branch, you will need to adjust your front door configuration on Azure.

Please check it out these following issues that may can help you:

#61 
#65

**Comment by cristianoag** [comment]
Make sure you're using the latest version available on GitHub.

**Comment by MarkusMGB** [comment]
@cristianoag thanks a lot! Problem solved with the changing the runtime version
