### ISSUE TITLE
Rederização da mensagem

### ISSUE THREAD

**Issue by CRVieiras** [cristianoag/microsoft-teams-apps-company-communicator#71]
Bom dia, @cristianoag tudo bem?

Percebemos que após atualização para versão v5.31, todas as mensagens enviadas estão chegando aos destinatarios com um quadrado em branco. Por gentileza, você tem alguma solução para esse comportamento?

![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/101516896/3de1a0d4-1a74-4800-aca9-211638592067)

**Comment by cristianoag** [comment]
We are checking that.

**Comment by luishdemetrio** [comment]
@CRVieiras , corrigido. por gentileza faça o sync do app service.
