### ISSUE TITLE
Status of 'read' does not count

### ISSUE THREAD

**Issue by Fadel1949** [cristianoag/microsoft-teams-apps-company-communicator#74]
The status of 'read' does not count the quantity when a user reads a post. However, the status of clicking the button occurs when a user clicks.
![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/126840838/996b7998-a261-4365-aa7e-5ed1eaf5da68)

Could you help test why it is like that?

**Comment by luishdemetrio** [comment]
Hi, is your version updated, i.e., when was the last time that you sync it via Azure Deployment Center? What is the branch that you are using? Please check the thread of the issue #68, as it can be related.

**Comment by Fadel1949** [comment]
@luishdemetrio 
 
last Deployment Center 24-Nov-2023
Repository
https://github.com/cristianoag/microsoft-teams-apps-company-communicator.git
Branch
master

**Comment by luishdemetrio** [comment]
Hi @Fadel1949, did you also change the settings of the Azure Front Door?

**Comment by Fadel1949** [comment]
@luishdemetrio  At first it hasn't changed. Now it's changed.
I'll check again after I change it.
